# Generated by Django 4.0.8 on 2024-12-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_newsandevents_posted_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='posted_as',
            field=models.CharField(choices=[('News', 'News'), ('Notes', 'Notes')], max_length=10),
        ),
    ]
