# Generated by Django 4.0.8 on 2025-01-11 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_date_of_birth_user_enrollment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningStyleTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('q1', models.CharField(max_length=1)),
                ('q2', models.CharField(max_length=1)),
                ('q3', models.CharField(max_length=1)),
                ('q4', models.CharField(max_length=1)),
                ('q5', models.CharField(max_length=1)),
                ('q6', models.CharField(max_length=1)),
                ('q7', models.CharField(max_length=1)),
                ('q8', models.CharField(max_length=1)),
                ('q9', models.CharField(max_length=1)),
                ('q10', models.CharField(max_length=1)),
                ('q11', models.CharField(max_length=1)),
                ('q12', models.CharField(max_length=1)),
                ('q13', models.CharField(max_length=1)),
                ('q14', models.CharField(max_length=1)),
                ('q15', models.CharField(max_length=1)),
                ('q16', models.CharField(max_length=1)),
                ('visual_score', models.IntegerField()),
                ('aural_score', models.IntegerField()),
                ('read_write_score', models.IntegerField()),
                ('kinesthetic_score', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'ordering': ['-date_taken'],
            },
        ),
    ]
