# Generated by Django 4.0.8 on 2025-01-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_methods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningstyletest',
            name='q1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='learningstyletest',
            name='q10',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='learningstyletest',
            name='q11',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='learningstyletest',
            name='q12',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='learningstyletest',
            name='q13',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='learningstyletest',
            name='q14',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='learningstyletest',
            name='q15',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='learningstyletest',
            name='q16',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='learningstyletest',
            name='q2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='learningstyletest',
            name='q3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='learningstyletest',
            name='q4',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='learningstyletest',
            name='q5',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='learningstyletest',
            name='q6',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='learningstyletest',
            name='q7',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='learningstyletest',
            name='q8',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='learningstyletest',
            name='q9',
            field=models.CharField(max_length=10),
        ),
    ]
