# Generated by Django 4.0.8 on 2025-01-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_code_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOffer',
        ),
    ]
