# Generated by Django 4.0.8 on 2024-12-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='enrollment_date',
            field=models.DateField(blank=True, help_text='Date the student enrolled in their current program', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ethnicity',
            field=models.CharField(blank=True, help_text="E.g., 'Hispanic', 'Asian', etc.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expected_graduation_date',
            field=models.DateField(blank=True, help_text='When the student expects to graduate', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='languages_spoken',
            field=models.TextField(blank=True, help_text="E.g., 'English, Spanish, French'", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, help_text='Passport or National ID number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, help_text="E.g., 'American', 'Canadian', etc.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.CharField(blank=True, help_text="E.g., 'Computer Science', 'Business Administration'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='religion',
            field=models.CharField(blank=True, help_text="E.g., 'Christianity', 'Islam', 'None'", max_length=50, null=True),
        ),
    ]
