# Generated by Django 4.0.8 on 2024-12-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('asian', 'Asian'), ('black', 'Black'), ('hispanic', 'Hispanic'), ('white', 'White'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expected_graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Faculty of Arts', 'Faculty of Arts'), ('Faculty of Science', 'Faculty of Science'), ('Faculty of Engineering', 'Faculty of Engineering'), ('Faculty of Medicine', 'Faculty of Medicine'), ('Faculty of Agriculture', 'Faculty of Agriculture'), ('Faculty of Law', 'Faculty of Law'), ('Faculty of Commerce', 'Faculty of Commerce'), ('Faculty of Education', 'Faculty of Education'), ('Faculty of Veterinary Medicine', 'Faculty of Veterinary Medicine'), ('Faculty of Dentistry', 'Faculty of Dentistry'), ('Faculty of Pharmacy', 'Faculty of Pharmacy'), ('Faculty of Physical Education', 'Faculty of Physical Education'), ('Faculty of Nursing', 'Faculty of Nursing'), ('Faculty of Computer Science', 'Faculty of Computer Science'), ('Faculty of Business Administration', 'Faculty of Business Administration'), ('Faculty of Fine Arts', 'Faculty of Fine Arts'), ('Faculty of Tourism and Hotels', 'Faculty of Tourism and Hotels'), ('Faculty of Environmental Sciences', 'Faculty of Environmental Sciences'), ('Faculty of Specific Education', 'Faculty of Specific Education'), ('Faculty of Oral and Dental Medicine', 'Faculty of Oral and Dental Medicine'), ('Higher Institute for Cooperative and Administrative Studies', 'Higher Institute for Cooperative and Administrative Studies'), ('Intermediate Institute of Social Service', 'Intermediate Institute of Social Service'), ('Institute of Administration, Secretarial Work and Computers', 'Institute of Administration, Secretarial Work and Computers'), ('Higher Institute of Languages and Translation', 'Higher Institute of Languages and Translation'), ('Higher Institute of Agricultural Cooperation and Guidance', 'Higher Institute of Agricultural Cooperation and Guidance'), ('Higher Institute of Computers, Administrative Information and Management Science', 'Higher Institute of Computers, Administrative Information and Management Science'), ('Higher Institute of Languages', 'Higher Institute of Languages'), ('Egyptian Higher Institute of Tourism and Hotels', 'Egyptian Higher Institute of Tourism and Hotels'), ('Higher Institute of Optic Technology', 'Higher Institute of Optic Technology'), ('Institute of Specific Studies', 'Institute of Specific Studies'), ('Higher Institute of Social Work', 'Higher Institute of Social Work'), ('Higher Institute of Agricultural Cooperation and Guidance', 'Higher Institute of Agricultural Cooperation and Guidance')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Egyption', 'Egyption'), ('american', 'American'), ('british', 'British'), ('canadian', 'Canadian'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='religion',
            field=models.CharField(blank=True, choices=[('christian', 'Christianity'), ('muslim', 'Islam'), ('jewish', 'Judaism'), ('hindu', 'Hinduism'), ('buddhist', 'Buddhism'), ('other', 'Other / Prefer not to say')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('High School', 'High School'), ('Middle School', 'Middle School'), ('Associate', 'Associate Degree'), ('Bachelor', 'Bachelor Degree'), ('Diploma', 'Diploma'), ('Master', 'Master Degree'), ('Doctorate', 'Doctorate Degree')], max_length=25, null=True),
        ),
    ]
