# Generated by Django 4.0.8 on 2025-01-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_delete_courseoffer'),
        ('accounts', '0003_user_date_of_birth_user_enrollment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.DeleteModel(
            name='DepartmentHead',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
