# Generated by Django 4.0.8 on 2025-01-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_date_of_birth_user_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_add_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_analyze_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_use_learning_method',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_use_path_finding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_students',
            field=models.BooleanField(default=False),
        ),
    ]
