# Generated by Django 4.0.8 on 2024-12-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_college_remove_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Egyption', 'Egyption'), ('american', 'American'), ('british', 'British'), ('canadian', 'Canadian'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
