# Generated by Django 5.1.4 on 2024-12-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='expected_graduation_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='languages_spoken',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='religion',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('asian', 'Asian'), ('black', 'Black'), ('hispanic', 'Hispanic'), ('white', 'White'), ('gay', 'Gay'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='expected_graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Egyption', 'Egyption'), ('american', 'American'), ('british', 'British'), ('canadian', 'Canadian'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('christian', 'Christianity'), ('muslim', 'Islam'), ('jewish', 'Judaism'), ('hindu', 'Hinduism'), ('buddhist', 'Buddhism'), ('other', 'Other / Prefer not to say')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
