# Generated by Django 4.0.8 on 2025-01-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path_finding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='career_prospects',
        ),
        migrations.RemoveField(
            model_name='program',
            name='requirements',
        ),
        migrations.AddField(
            model_name='testsession',
            name='llm_analysis',
            field=models.TextField(blank=True, verbose_name='Career Analysis Results'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='q10_goals',
            field=models.TextField(blank=True, verbose_name='Educational goals'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='q1_numbers',
            field=models.CharField(blank=True, max_length=255, verbose_name='Working with numbers preference'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='q2_math',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mathematical abilities'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='q3_problem_solving',
            field=models.CharField(blank=True, max_length=255, verbose_name='Problem solving approach'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='q4_future_job',
            field=models.TextField(blank=True, verbose_name='Future job preference'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='q5_tools',
            field=models.CharField(blank=True, max_length=255, verbose_name='Preferred tools'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='q6_tech_interest',
            field=models.CharField(blank=True, max_length=255, verbose_name='Technology interests'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='q7_learning',
            field=models.CharField(blank=True, max_length=255, verbose_name='Learning preference'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='q8_computer_skills',
            field=models.CharField(blank=True, max_length=255, verbose_name='Computer skills level'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='q9_projects',
            field=models.CharField(blank=True, max_length=255, verbose_name='Project interests'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
