# Generated by Django 4.0.8 on 2025-01-14 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_date_of_birth_user_enrollment_date_and_more'),
        ('path_finding', '0002_remove_program_career_prospects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathFindingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
